### PR TITLE
fix(websocket): handle errors in handleUpgrade

### LINKED ISSUE #822: Errors in prepareProxyRequest not handled for websockets
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

The callsites of `handleUpgrade` do not handle errors thrown from `prepareProxyRequest`. For a user, this means that any error thrown in `router` or `pathRewrite` will result in an `unhandledRejection`.

We can see that the two call sites for `handleUpgrade` neither `await` the returned promise, nor use `.catch()` to handle errors:

https://github.com/chimurai/http-proxy-middleware/blob/79c9885eb2b8ed1bc201182175b733b738873f5e/src/http-proxy-middleware.ts#L34

https://github.com/chimurai/http-proxy-middleware/blob/79c9885eb2b8ed1bc201182175b733b738873f5e/src/http-proxy-middleware.ts#L88

### Step-by-step reproduction instructions

Add a `router` or `pathRewrite` function that throws an error, then try to make a websocket request. Observe that the error is not handled. E.g., if you add an `onError` handler to the proxy config, it is not called, and if you `process.on('unhandledRejection', (e) => console.error(e))`, that error is logged.

### Expected behavior (be clear and concise)

`onError` should be invoked so that I can handle the error appropriately.

### How is http-proxy-middleware used in your project?

It is installed as a direct dependency.

### What http-proxy-middleware configuration are you using?

Here's a pared-down version:

```typescript
const options = {
  router: async () => {
    throw new Error('testing');
  },
  onError: (err, req, res) => {
    // Not called for websocket requests
    res.status(500).send();
  },
};
```

### What OS/version and node/version are you seeing the problem?

```shell
macOS 12.5.1; Node v16.17.0
```

### PR DESCRIPTION
**Pull request by nwalters512**
## Description

When there is an error from user-provided code (`pathFilter`, `rewritePath`, or `router`), that error is now handled and exposed to the user via `proxy.emit('error', ...)`.

`error-response-plugin` was also updated to handle the fact that it might receive a socket. If it does, it will call `socket.destroy()`.

## Motivation and Context

See #822 for a description of the issue being fixed. This PR closes #822.

## How has this been tested?

I added a new test case. It fails on master, and works correctly with my new changes.

## Types of changes

I'm split on whether or not this should be considered a breaking change. Folks could have written code assuming that the error handler would always get a `Response` as the third argument, whereas now it would get a `Socket`. That said, the TypeScript types from `http-proxy` do reflect that that could be a `Socket`, so it shouldn't come as too much of a surprise.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

<a href="https://gitpod.io/#https://github.com/chimurai/http-proxy-middleware/pull/823"></a>

### CODE REVIEW

File: src/plugins/default/error-response-plugin.ts [hunk 1]
```diff
@@ -1,19 +1,32 @@
...
 import { getStatusCode } from '../../status-code';
 import { Plugin, Response } from '../../types';
 
+function isResponseLike(obj: any): obj is Response {
+  return obj && typeof obj.writeHead === 'function';
+}
+
+function isSocketLike(obj: any): obj is Socket {
+  return obj && typeof obj.write === 'function' && !('writeHead' in obj);
+}
```
Comment (nwalters512) [inline src/plugins/default/error-response-plugin.ts:11]: We can't just check for `instanceof Socket` since per [the documentation](https://nodejs.org/api/http.html#event-upgrade), the user may be able to provide a different socket implementation:

> This event is guaranteed to be passed an instance of the [<net.Socket>](https://nodejs.org/api/net.html#class-netsocket) class, a subclass of [<stream.Duplex>](https://nodejs.org/api/stream.html#class-streamduplex), unless the user specifies a socket type other than [<net.Socket>](https://nodejs.org/api/net.html#class-netsocket).

File: test/e2e/websocket.spec.ts [hunk 2]
```diff
@@ -97,15 +97,14 @@ describe('E2E WebSocket proxy', () => {
 
   describe('with router and pathRewrite', () => {
     beforeEach(() => {
-      // override
-      proxyServer = createApp(
+      const proxyMiddleware = createProxyMiddleware({
```
Comment (nwalters512) [inline test/e2e/websocket.spec.ts:100]: This was a bug with the existing tests: because it didn't reassign `proxyMiddleware`, the `proxyMiddleware.upgrade` access a few lines after this was reading from the wrong object.

**Comment by nwalters512** [comment]
@chimurai 👋 can I do anything to help this along?

**Comment by chimurai** [comment]
Sorry for the late reply. I'll need some time to review 🙏

**Comment by nwalters512** [comment]
@chimurai thanks!

**Comment by nwalters512** [comment]
@chimurai is there any chance you'd be able to review soon? If so, I'll resolve the merge conflicts with master.

**Comment by nwalters512** [comment]
@chimurai sorry to poke again, but I'd like to understand if there's a chance that this will be merged, or if I'll have to fork. Thanks for your work maintaining this package!

**Comment by chimurai** [comment]
Thanks for the PR and patience @nwalters512  🙏

Could you verify if your fix works with the package preview from `pkg-pr-new`?

**Comment by chimurai** [comment]
Hope the following guides are helpful to upgrade:

https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md
V3 Discussions: https://github.com/chimurai/http-proxy-middleware/discussions/768

Let me know if you bump into issues 🙏

**Comment by nwalters512** [comment]
@chimurai I got myself upgraded and tried out this PR, it's working exactly how I want it to 🙏 I added some artificial errors to the bits of my code that deal with websocket routing and confirmed that they're now passes to the error handler I configured.

**Comment by nwalters512** [comment]
@chimurai for my own planning, do you have a plan for when you'll cut the next release with this change?

**Comment by chimurai** [comment]
Hi @nwalters512. I hope to create a release somewhere this week.
